name: Process MDX Pull Requests

on:
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:

  convert-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install jekyll
        gem install jekyll-mdx

    - name: Convert YAML to MDX
      run: |
        mkdir -p _posts
        for file in ${{ github.event.pull_request.head.repo.full_name }}/*.y*ml; do
          filename=$(basename "$file")
          yaml2mdx "$file" > "_posts/$(date +'%Y-%m-%d')-${filename%.y*ml}.markdown"
        done

    - name: Build Jekyll site
      run: |
        jekyll build --config _config.yml

    - name: Start Jekyll server
      run: |
        jekyll serve --skip-initial-build --host 0.0.0.0 &
        sleep 3
        curl http://0.0.0.0:4000

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-site
        path: _site/
